spring: 
    profiles: 
        active: 
            - dev

---
server: 
    port: 8001
    
spring: 
    profiles: dev
    application: 
        name: microservicecloud-config-dept-client
    datasource: 
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3388/jdbc?serverTimezone=UTC
        driver-class-name: com.mysql.jdbc.Driver
        
mybatis:
    type-aliases-package: com.xiaoer.springcloud.entities
    mapper-locations: 
        - classpath:mybatis/mapper/**/*.xml
        
eureka:
    client:
    service-url:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
        instance-id: microservicecloud-dept8001
        prefer-ip-address: true
        
info:
    app.name: xiaoer-microservicecloud
    company.name: www.xiaoer.com
    build.artifaceId: $project.artifactId$
    build.version: $project.version$

---
server: 
    port: 8002
    
spring: 
    profiles: test
    application: 
        name: microservicecloud-config-dept-client
    datasource: 
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3388/jdbc?serverTimezone=UTC
        driver-class-name: com.mysql.jdbc.Driver
        
mybatis:
    type-aliases-package: com.xiaoer.springcloud.entities
    mapper-locations: 
        - classpath:mybatis/mapper/**/*.xml
        
eureka:
    client:
    service-url:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
        instance-id: microservicecloud-dept8001
        prefer-ip-address: true
        
info:
    app.name: xiaoer-microservicecloud
    company.name: www.xiaoer.com
    build.artifaceId: $project.artifactId$
    build.version: $project.version$